version: "3.6"
services:

  nginx:
    build: nginx/
    ports:
      - "8080:80"
    links:
      - php

  php:
    build: php/
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /key.json
    env_file:
      - php/.env
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/key.json:ro
      - ./php:/src
